#!/bin/csh -vx


echo ""> tablaPCLOCAL4THREADsec.dat
@ i = 0
while ( $i < 1200)
	echo " $i `./secuencial $i`" >> tablaPCLOCAL4THREADsec.dat
@ i += 100
end

echo ""> tablaPCLOCAL4THREADpara1.dat
@ i = 0
while ( $i < 1200)
	echo " $i `./paralelo1 $i`" >> tablaPCLOCAL4THREADpara1.dat
@ i += 100
end

echo ""> tablaPCLOCAL4THREADpara2.dat
@ i = 0
while ( $i < 1200)
	echo " $i `./paralelo2 $i`" >> tablaPCLOCAL4THREADpara2.dat
@ i += 100
end

echo ""> tablaPCLOCAL4THREADpara3.dat
@ i = 0
while ( $i < 1200)
	echo " $i `./paralelo3 $i`" >> tablaPCLOCAL4THREADpara3.dat
@ i += 100
end
